name: Publish to PyPI

on:
  release:
    types: [ published ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  cd:

    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2

    - name: Check-out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Build documentation
      run: poetry run make html --directory docs/

    # Configuring and attempting to install from TestPyPI
    - name: Configure poetry for TestPyPI
      env:
        test_pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.pypi $test_pypi_token

    - name: Build with poetry 
      run: poetry publish --build -r testpypi

    # - name: Publish with poetry to TestPyPI
    #   run: poetry publish -r testpypi

    - name: Test install from TestPyPI
      run: pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple sc2_datasets

    # Upload to PyPI only if everything else is correct:
    - name: Configure poetry with PyPI Token
      env:
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry config pypi-token.pypi $pypi_token

    - name: Build and publish to PyPI
      run: poetry publish --build
